language: node_js

node_js:
 - 4
 - 6
 - 7

env:
  - BABEL_ENV=test

matrix:
  fast_finish: true

cache:
  directories:
    - node_modules

before_script:
  - npm prune
  - BABEL_ENV=v4 npm run compile -- -d lib/node4
  - BABEL_ENV=v6 npm run compile -- -d lib/node6
  - BABEL_ENV=v7 npm run compile -- -d lib/node7
  - BABEL_ENV=browser npm run compile -- -d lib/browser

after_success:
  - npm run coverage
  - npm run codeclimate
  - npm run semantic-release

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
    - /^greenkeeper\/.+/
